[tool.poetry]
name = "langroid-examples"
version = "0.1.0"
description = ""
authors = ["Prasad Chalasani <pchalasani@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "examples"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
langroid = {version="^0.1.154", extras = ["litellm", "hf-embeddings", "postgres", "mysql"]}
chainlit = "^0.7.700"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
